// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD3jnsMWP1ZgH3igQBePSoyzexxTCxClg',
    appId: '1:589898369862:web:46b94cfca53ac87a557347',
    messagingSenderId: '589898369862',
    projectId: 'cricketlivescore-2094e',
    authDomain: 'cricketlivescore-2094e.firebaseapp.com',
    storageBucket: 'cricketlivescore-2094e.appspot.com',
    measurementId: 'G-2YWD7CPLTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbPaSCSXtzBMofgwW1bEEFjadU5FpH7yQ',
    appId: '1:589898369862:android:a6bd416b2ffe0aa6557347',
    messagingSenderId: '589898369862',
    projectId: 'cricketlivescore-2094e',
    storageBucket: 'cricketlivescore-2094e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWrlkJSL3lKNINYzHPH-s_IcPQZMelAGI',
    appId: '1:589898369862:ios:bb1ab0312bf0963b557347',
    messagingSenderId: '589898369862',
    projectId: 'cricketlivescore-2094e',
    storageBucket: 'cricketlivescore-2094e.appspot.com',
    iosBundleId: 'com.cricketscore.livescore',
  );
}
